### PR TITLE
use maven cache

### PR DESCRIPTION
**Pull request by darkspirit510**
I prefer using cache for dependencies... 🙈

### CODE REVIEW

**Comment by davewichers** [comment]
What does 'cache: maven' do?

**Comment by darkspirit510** [comment]
In short: Setup cache in background so maven does not have to download all the dependencies on each action run.

```
The action has a built-in functionality for caching and restoring dependencies. It uses actions/cache under hood for caching dependencies but requires less configuration settings. Supported package managers are gradle and maven. The cache input is optional, and caching is turned off by default.
```
Source: https://github.com/actions/setup-java

**Comment by davewichers** [comment]
Any clue how I test this myself to make sure it works/doesn't break anything before I merge this change in?

**Comment by darkspirit510** [comment]
I guess for security reasons GitHub actions don't run on pull requests. You can see the the cache in action in my branch:

https://github.com/darkspirit510/BenchmarkUtils/runs/5034543172?check_suite_focus=true

(Expand `Set up JDK 1.8`)

**Pull request merged**
