### PR TITLE
Mend reader

### PR DESCRIPTION
**Pull request by darkspirit510**
As discussed via mail ✉️

### CODE REVIEW

**Comment by davewichers** [comment]
@darkspirit510 - do you think you'll get a chance to look into this anytime soon?

**Comment by davewichers** [comment]
@darkspirit510 - If you researched, can you post your questions/research here? If you sent me emails about it directly, it's too easy to get lost/overlooked, so please post here if you did.

**Comment by darkspirit510** [comment]
@darkspirit510 as requested, from my mail: 

From what I can see (comparing MendReader and XanitizerReader), Mend and Xanitizer result files seems to be completly different, so no chance of merging them to one reader. Since I don't have access to a Xanitizer result file, I can't check this assumption.

**Comment by davewichers** [comment]
@darkspirit510 - Xanitizer is super old. I think we should actually drop/delete that one and replace it with this new one. Can you implement that removal in this pull request? Other than that, do you think the new Mend Reader is ready to go? If so, I'll merge once you include the Xanitizer removal.

**Comment by darkspirit510** [comment]
```
Xanitizer is super old. I think we should actually drop/delete that one and replace it with this new one. Can you implement that removal in this pull request?
```
Done

```
Other than that, do you think the new Mend Reader is ready to go?
```
Yes (at least the file I got hands on can be parsed without errors and results in a non-zero scorecard)

**Pull request merged**
