### PR TITLE
fix HCL AppScan Source reader

### PR DESCRIPTION
**Pull request by mattmurp**

### CODE REVIEW

**Comment by darkspirit510** [comment]
Hi Matt(murp),
thank you for the PR. The code you submitted looks good, but I can't tell, if it works. Can you please either add a small test class for the AppScanSourceReader or, even better, send me a (real) result file github@darkspirit510.de? I can offer to write a test with a reduced/censored file and review the change with it.
Sascha

**Comment by mattmurp** [comment]
Thanks Sascha. I sent you a sample xml file. Let me know if there's anything else you need.

**Comment by darkspirit510** [comment]
You've got mail 😉 one additional thing, I just noticed (can't comment it via GitHub): The tool is named HCL, but in the code it says IBM. I guess this is not right (anymore). Can you check this?

**Comment by davewichers** [comment]
@mattmurp - Can you address @darkspirit510's comments?

**Comment by mattmurp** [comment]
Sorry for the delay. I just pushed the requested updates.

**Comment by davewichers** [comment]
@darkspirit510 - You OK with this now, approve the merge?

**Comment by darkspirit510** [comment]
@davewichers yes! 👍

**Comment by mattmurp** [comment]
Hi @davewichers and @darkspirit510 can this be merged now? Thanks.

**Pull request merged**
