### PR TITLE
AppScan was owned by HCL now

### PR DESCRIPTION
**Pull request by arunmuthu255**
IBM AppScan become HCL AppScan

### CODE REVIEW

**Comment by davewichers** [comment]
Thanks! Do you want to update the AppScan DAST parser too? I suspect it still refers to IBM as well.

**Comment by arunmuthu255** [comment]
Hi Dave, the code change which I have pushed is for AppScan DAST parser. Are you referring to AppScan SAST ?

**Comment by davewichers** [comment]
I guess I had them backwards, so yes.

**Comment by arunmuthu255** [comment]
Okay

**Pull request merged**
