### PR TITLE
Positive Technologies Application Inspector (PT AI) SARIF report support

### PR DESCRIPTION
**Pull request by ZhukovAN**
PT AI SARIF report support added

### CODE REVIEW

**Comment by darkspirit510** [comment]
Hi @ZhukovAN,
thank you for the contribution. The code looks good, nothing to complain from my side. Just one thing - could you provide a complete result file to either me (github@darkspirit510.de) or @davewichers (dave.wichers@owasp.org) so we can verify everything works as expected? Don't worry, the file obviously won't be published anywhere!
Sascha

**Comment by ZhukovAN** [comment]
Hi! Sure, check your mail boxes

**Comment by darkspirit510** [comment]
Hi @ZhukovAN,
thank you for the file! It can be read without errors. But I have a minor issue. Could you abbreviate the display name? `Positive Technologies Application Inspector` underflows the percentage and version number, it's hard to read in the `toolresults_comparison.png` file.
Sascha

**Comment by ZhukovAN** [comment]
Does "PT Application Inspector" fits flawlessly?

**Comment by ZhukovAN** [comment]
Hi! I've shortened tool name and also removed build number from version info to make it shorted. I think now benchmark comparison chart looks perfect :)
toolresults_comparison

**Comment by darkspirit510** [comment]
Hi @ZhukovAN,
looks good to me! @davewichers this can be merged, if you agree.

PS: @ZhukovAN be careful when posting results of commercial tools (unless you have been authorized to do so 😉)
Sascha

**Pull request merged**
